services:
  trino:
    image: trinodb/trino:latest
    container_name: trino
    hostname: trino
    depends_on:
      lakekeeper:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./etc/trino/catalog:/etc/trino/catalog
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/info"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - lakehouse-network

networks:
  lakehouse-network:
    driver: bridge
    name: shared-data-network