lakehouse_profile: 
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: ilaybor
      password: ""
      
      host: trino
      port: 8080
      catalog: iceberg
      schema: ""
      threads: 1
      client_tags:
        - dbt